### ISSUE TITLE
Use SoftDeletes on Flags model

### ISSUE THREAD

**Issue by jpswade** [spatie/laravel-model-flags#7]
I'd like to suggest using SoftDeletes on the Flags model.

This means that when flags are deleted you still have the original record of when the flag was added.

For example, you can mark a model (eg: a User) as “receivedMail”, however without soft deletes, if you decide to remove this flag, you wouldn't know when it was added or removed.

Using soft deletes would act as a log of not only when a flag was applied, but when it was deleted, providing an event history of the flags, making debugging flags related issues much easier as you could see the events over time.

**Comment by freekmurze** [comment]
Feel free to use a custom modal and use the soft deletes trait on that.
