### ISSUE TITLE
Suggestion for adding Properties field for context

### ISSUE THREAD

**Issue by rumspeed** [spatie/laravel-model-flags#8]
The new package is great. Would you consider adding a properties field for additional context. This is a feature that is in your Activity Log package and proves to be quite useful. This would extend the use cases for this great new package.

### Add to migration

`$table->json('properties')->nullable();`

### Method to add data

`$user->flag('receivedMail')->withProperties(['customProperty' => 'customValue']);`

**Comment by freekmurze** [comment]
Thanks for the suggestion but I want to keep this package as simple as it can be. Feel free to use a custom model and add any extra behaviour you need on that model in your project.
